---
name: Salt
version: "0.15.2"
slug: salt
description: Run a persistent Salt master and expose Salt minions to Home Assistant.
url: https://github.com/Akm0d/hassio-app-salt
startup: services
boot: auto
init: false
protected: false
docker_api: true
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:shaker-outline
panel_title: Salt
panel_admin: true
arch:
  - aarch64
  - amd64
map:
  - type: share
    read_only: false
    path: /srv
  - type: homeassistant_config
    read_only: false
    path: /config
ports:
  4505/tcp: 4505
  4506/tcp: 4506
ports_description:
  4505/tcp: Salt publish port
  4506/tcp: Salt return port
options:
  ui:
    host: 0.0.0.0
    port: 8099
  docker_proxy:
    enabled: true
    include_stopped: true
  master:
    log_level: info
    auto_accept: false
    worker_threads: 8
    publish_port: 4505
    ret_port: 4506
schema:
  ui:
    host: str
    port: int
  docker_proxy:
    enabled: bool
    include_stopped: bool
  master:
    log_level: list(trace|debug|info|notice|warning|error|fatal)
    auto_accept: bool
    worker_threads: int
    publish_port: port
    ret_port: port
